apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    app: kubernetes-dashboard
spec:
  type: ClusterIP
  selector:
    app: kubernetes-dashboard
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
