apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../k8s

images:
  - name: ghcr.io/dlddu/kubernetes-dashboard
    newName: kubernetes-dashboard
    newTag: e2e

patches:
  - target:
      kind: Deployment
      name: kubernetes-dashboard
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
        value: 10
  - target:
      kind: Service
      name: kubernetes-dashboard
    patch: |
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30080
